CREATE TABLE MEMBER
(	
    MEMBERID VARCHAR2(20 BYTE) NOT NULL PRIMARY KEY, -- varchar -> varchar2(갯수, byte or char)
	PASSWD VARCHAR2(100 BYTE) NOT NULL, 
	EMAIL VARCHAR2(50 BYTE) NOT NULL, 
	USERTYPE VARCHAR2(50 BYTE) DEFAULT ('user') CHECK (USERTYPE IN ('user', 'admin')), 
	REGDATE DATE DEFAULT (SYSDATE), -- NOW() -> SYSDATE
	ACTIVE CHAR(1 BYTE) DEFAULT ('1') -- boolean -> char(1)
);
  
CREATE TABLE BOARD
(	
    BOARDNO NUMBER NOT NULL, 
	TITLE VARCHAR2(100 CHAR) NOT NULL,   -- 100 개의 문자 저장
	WRITER VARCHAR2(20 BYTE) NOT NULL,   --  20 BYTE의 문자 데이터 저장
	CONTENT VARCHAR2(4000 CHAR) NOT NULL, 
	REGDATE DATE DEFAULT (SYSDATE), 
	READCOUNT NUMBER DEFAULT (0), 
	DELETED CHAR(1 BYTE) DEFAULT ('0'),
    CONSTRAINT PK_BOARD PRIMARY KEY (BOARDNO),
    CONSTRAINT FK_BOARD_TO_MEMBER FOREIGN KEY (WRITER) REFERENCES MEMBER(MEMBERID)
);

CREATE SEQUENCE BOARD_SEQUENCE NOCACHE ;

SELECT BOARD_SEQUENCE.NEXTVAL FROM DUAL; -- 자동증가번호생성기에서 다음 번호 뽑기
SELECT BOARD_SEQUENCE.CURRVAL FROM DUAL; -- 자동증가번호생성기에서 마지막으로 뽑은 번호 읽기

CREATE TABLE BOARDATTACH
(	
    ATTACHNO NUMBER NOT NULL, 
	BOARDNO NUMBER NOT NULL, 
	USERFILENAME VARCHAR2(100 CHAR) NOT NULL, 
	SAVEDFILENAME VARCHAR2(100 BYTE) NOT NULL, 
	DOWNLOADCOUNT NUMBER DEFAULT (0),
    CONSTRAINT PK_BOARDATTACH PRIMARY KEY (ATTACHNO),
    CONSTRAINT FK_BOARDATTACH_TO_BOARD FOREIGN KEY (BOARDNO) REFERENCES BOARD(BOARDNO)
);

CREATE SEQUENCE BOARDATTACH_SEQUENCE NOCACHE;

CREATE TABLE BOARDCOMMENT
(
    COMMENTNO NUMBER NOT NULL, 
	BOARDNO NUMBER NOT NULL, 
	WRITER VARCHAR2(20 BYTE) NOT NULL, 
	CONTENT VARCHAR2(1000 CHAR), 
	REGDATE DATE DEFAULT (SYSDATE), 
	DELETED CHAR(1 BYTE) DEFAULT ('0'), 
	GROUPNO NUMBER NOT NULL, 
	STEP NUMBER NOT NULL, 
	DEPTH NUMBER NOT NULL,
    CONSTRAINT PK_BOARDCOMMENT PRIMARY KEY (COMMENTNO),
    CONSTRAINT FK_BOARDCOMMENT_TO_MEMBER FOREIGN KEY (WRITER) REFERENCES MEMBER(MEMBERID),
    CONSTRAINT FK_BOARDCOMMENT_TO_BOARD FOREIGN KEY (BOARDNO) REFERENCES BOARD(BOARDNO)
);

CREATE SEQUENCE BOARDCOMMENT_SEQUENCE NOCACHE;
